using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.ComponentModel;
using System.Windows.Forms;

namespace MUDEngine.Objects
{
    public class BaseObject
    {
        public virtual void OnEnter(object sender, EventArgs e)
        {
        }

        [Category("Object Setup")]
        [RefreshProperties(RefreshProperties.All)] //Required to refresh Filename property in the editors propertygrid
        public string Name
        {
            get;
            set;
        }

        [Category("Object Setup")]
        public string Description
        {
            get;
            set;
        }

        [Browsable(false)]
        public string Script { get; set; }

        [ReadOnly(true)]
        [Category("Object Setup")]
        public string Filename
        {
            //Returns the name of the object + the objects Type as it's extension.
            //Filenames are generated by the class itself, users can not assign it.
            get
            {
                string fileExtension = this.GetType().Name.ToLower();

                return this.Name + "." + fileExtension;
            }
        }

        /// <summary>
        /// Initializes the base object
        /// </summary>
        public BaseObject()
        {
        }
    }
}
