//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MudDesigner.Engine.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    public sealed partial class EngineSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static EngineSettings defaultInstance = ((EngineSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new EngineSettings())));
        
        public static EngineSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MudDesigner.Scripts.Default.Game.DefaultGame")]
        public string DefaultGameType {
            get {
                return ((string)(this["DefaultGameType"]));
            }
            set {
                this["DefaultGameType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MudDesigner.Scripts.Default.Environment.DefaultWorld")]
        public string DefaultWorldType {
            get {
                return ((string)(this["DefaultWorldType"]));
            }
            set {
                this["DefaultWorldType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MudDesigner.Scripts.Default.Mobs.DefaultPlayer")]
        public string DefaultPlayerType {
            get {
                return ((string)(this["DefaultPlayerType"]));
            }
            set {
                this["DefaultPlayerType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MudDesigner.Scripts.Default.States.MainMenuState")]
        public string LoginSuccessState {
            get {
                return ((string)(this["LoginSuccessState"]));
            }
            set {
                this["LoginSuccessState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection ScriptLibrary {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ScriptLibrary"]));
            }
            set {
                this["ScriptLibrary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Scripts")]
        public string ScriptsPath {
            get {
                return ((string)(this["ScriptsPath"]));
            }
            set {
                this["ScriptsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bedroom")]
        public string LoginRoom {
            get {
                return ((string)(this["LoginRoom"]));
            }
            set {
                this["LoginRoom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MudDesigner.Scripts.Default.Environment.DefaultDoor")]
        public string DoorType {
            get {
                return ((string)(this["DoorType"]));
            }
            set {
                this["DoorType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MudDesigner.Scripts.Default.Environment.DefaultRealm")]
        public string RealmType {
            get {
                return ((string)(this["RealmType"]));
            }
            set {
                this["RealmType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MudDesigner.Scripts.Default.Environment.DefaultZone")]
        public string ZoneType {
            get {
                return ((string)(this["ZoneType"]));
            }
            set {
                this["ZoneType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MudDesigner.Scripts.Default.Environment.DefaultRoom")]
        public string RoomType {
            get {
                return ((string)(this["RoomType"]));
            }
            set {
                this["RoomType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("World.sav")]
        public string WorldFile {
            get {
                return ((string)(this["WorldFile"]));
            }
            set {
                this["WorldFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MudDesigner.Scripts.Default.States.Login.ClientConnectState")]
        public string InitialState {
            get {
                return ((string)(this["InitialState"]));
            }
            set {
                this["InitialState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Players")]
        public string PlayerSavePath {
            get {
                return ((string)(this["PlayerSavePath"]));
            }
            set {
                this["PlayerSavePath"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0.2.0")]
        public string Version {
            get {
                return ((string)(this["Version"]));
            }
        }
    }
}
