//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MudDesigner.Engine.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    public sealed partial class EngineSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static EngineSettings defaultInstance = ((EngineSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new EngineSettings())));
        
        public static EngineSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MudDesigner.Scripts.Default.Game.DefaultGame")]
        public string GameScript {
            get {
                return ((string)(this["GameScript"]));
            }
            set {
                this["GameScript"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MudDesigner.Scripts.Default.Environment.DefaultWorld")]
        public string WorldScript {
            get {
                return ((string)(this["WorldScript"]));
            }
            set {
                this["WorldScript"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MudDesigner.Scripts.Default.Mobs.DefaultPlayer")]
        public string PlayerScript {
            get {
                return ((string)(this["PlayerScript"]));
            }
            set {
                this["PlayerScript"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MudDesigner.Scripts.Default.States.LookingState")]
        public string LoginCompletedState {
            get {
                return ((string)(this["LoginCompletedState"]));
            }
            set {
                this["LoginCompletedState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection ScriptLibrary {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ScriptLibrary"]));
            }
            set {
                this["ScriptLibrary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Scripts")]
        public string ScriptsPath {
            get {
                return ((string)(this["ScriptsPath"]));
            }
            set {
                this["ScriptsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("New Realm1>New Zone1>New Room1")]
        public string InitialRoom {
            get {
                return ((string)(this["InitialRoom"]));
            }
            set {
                this["InitialRoom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MudDesigner.Scripts.Default.Environment.DefaultDoor")]
        public string DoorScript {
            get {
                return ((string)(this["DoorScript"]));
            }
            set {
                this["DoorScript"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MudDesigner.Scripts.Default.Environment.DefaultRealm")]
        public string RealmScript {
            get {
                return ((string)(this["RealmScript"]));
            }
            set {
                this["RealmScript"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MudDesigner.Scripts.Default.Environment.DefaultZone")]
        public string ZoneScript {
            get {
                return ((string)(this["ZoneScript"]));
            }
            set {
                this["ZoneScript"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MudDesigner.Scripts.Default.Environment.DefaultRoom")]
        public string RoomScript {
            get {
                return ((string)(this["RoomScript"]));
            }
            set {
                this["RoomScript"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("World.sav")]
        public string WorldSaveFile {
            get {
                return ((string)(this["WorldSaveFile"]));
            }
            set {
                this["WorldSaveFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MudDesigner.Scripts.Default.States.Login.ClientConnectState")]
        public string LoginState {
            get {
                return ((string)(this["LoginState"]));
            }
            set {
                this["LoginState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Players")]
        public string PlayerSavePath {
            get {
                return ((string)(this["PlayerSavePath"]));
            }
            set {
                this["PlayerSavePath"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0.2.0")]
        public string Version {
            get {
                return ((string)(this["Version"]));
            }
        }
    }
}
